
name: 'nadhafah_ops'
version: '1.0.0'
config-version: 2

profile: 'nadhafah_ops'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

models:
  nadhafah_ops:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
